apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft-server
        image: "<YOUR_AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/my-minecraft-server:1.0"
        ports:
        - containerPort: 25565 
        resources:
          requests:
            memory: "4Gi" 
            cpu: "1000m"  
          limits:
            memory: "6Gi" 
            cpu: "2000m"  